title: Lucas Munhoz - Javascript Development and Enginnering
baseurl: ""

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-59513662-1
disqus_shortname:

exclude: [node_modules, gulpfile.js]