# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lucas Munhoz - Javacript Expert
description: 
   I am a full stack developer with 5+ years of experience. 
   I love to create stuff for the web and discover new technologies. 
   I have a strong background with JavaScript, Meteor, MongoDB and React.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lnmunhoz
github_username:  lnmunhoz
google_analytics: UA-59513662-1

contact_email: ln.munhoz@gmail.com

contact_links:
- url: https://github.com/lnmunhoz
  title: Github
  username: lnmunhoz
- url: https://twitter.com/lnmunhoz
  title: Twitter
  username: lnmunhoz
- url: https://www.codementor.io/lnmunhoz
  title: Codementor
  username: lnmunhoz
- url: https://www.linkedin.com/in/lucasnmunhoz/
  title: Linkedin
  username: lucasnmunhoz
- url: https://www.toptal.com/resume/lucas-nogueira-munhoz
  title: Toptal
  username: lucas-nogueira-munhoz
- url: https://nomadlist.com/@lnmunhoz
  title: Nomadlist
  username: lnmunhoz
  
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

navigation:
- text: ME
  url: /
- text: ABOUT
  url: /about/
- text: CONNECT
  url: /connect/
# - text: PROJECTS
#  url: /projects/
